#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Standard14FontKind {
    Courier,
    Helvetica,
    HelveticaBold,
    TimesRoman,
}

#[inline]
pub(crate) fn supports_standard_14_font(base_font: &str) -> bool {
    standard_14_font_kind(base_font).is_some()
}

#[inline]
pub(crate) fn standard_14_font_width(base_font: &str, ch: char) -> Option<i32> {
    match standard_14_font_kind(base_font)? {
        Standard14FontKind::Courier => courier_width(ch),
        Standard14FontKind::Helvetica => helvetica_width(ch),
        Standard14FontKind::HelveticaBold => helvetica_bold_width(ch),
        Standard14FontKind::TimesRoman => times_roman_width(ch),
    }
}

fn standard_14_font_kind(base_font: &str) -> Option<Standard14FontKind> {
    match base_font {
        "Courier" => Some(Standard14FontKind::Courier),
        "Helvetica" => Some(Standard14FontKind::Helvetica),
        "Helvetica-Bold" => Some(Standard14FontKind::HelveticaBold),
        "Times-Roman" => Some(Standard14FontKind::TimesRoman),
        _ => None,
    }
}

fn courier_width(ch: char) -> Option<i32> {
    if ch.is_control() {
        return None;
    }
    Some(600)
}

fn helvetica_width(ch: char) -> Option<i32> {
    match ch {
        'á' | 'à' | 'â' | 'ä' | 'ã' => Some(556),
        'é' | 'è' | 'ê' | 'ë' => Some(556),
        'í' | 'ì' | 'î' | 'ï' => Some(278),
        'ó' | 'ò' | 'ô' | 'ö' | 'õ' => Some(556),
        'ú' | 'ù' | 'û' | 'ü' => Some(556),
        'ý' | 'ÿ' => Some(500),
        'Á' | 'À' | 'Â' | 'Ä' | 'Ã' => Some(667),
        'É' | 'È' | 'Ê' | 'Ë' => Some(667),
        'Í' | 'Ì' | 'Î' | 'Ï' => Some(278),
        'Ó' | 'Ò' | 'Ô' | 'Ö' | 'Õ' => Some(778),
        'Ú' | 'Ù' | 'Û' | 'Ü' => Some(722),
        'Ý' => Some(667),
        'ø' => Some(611),
        'Ø' => Some(778),
        'Ł' => Some(556),
        'ł' => Some(222),
        'ń' | 'ñ' => Some(556),
        'Ñ' => Some(722),
        '–' => Some(556),
        '—' => Some(1000),
        '’' => Some(222),
        ' ' => Some(278),
        '!' => Some(278),
        '"' => Some(355),
        '#' => Some(556),
        '$' => Some(556),
        '%' => Some(889),
        '&' => Some(667),
        '\'' => Some(191),
        '(' => Some(333),
        ')' => Some(333),
        '*' => Some(389),
        '+' => Some(584),
        ',' => Some(278),
        '-' => Some(333),
        '.' => Some(278),
        '/' => Some(278),
        '0' => Some(556),
        '1' => Some(556),
        '2' => Some(556),
        '3' => Some(556),
        '4' => Some(556),
        '5' => Some(556),
        '6' => Some(556),
        '7' => Some(556),
        '8' => Some(556),
        '9' => Some(556),
        ':' => Some(278),
        ';' => Some(278),
        '<' => Some(584),
        '=' => Some(584),
        '>' => Some(584),
        '?' => Some(556),
        '@' => Some(1015),
        'A' => Some(667),
        'B' => Some(667),
        'C' => Some(722),
        'D' => Some(722),
        'E' => Some(667),
        'F' => Some(611),
        'G' => Some(778),
        'H' => Some(722),
        'I' => Some(278),
        'J' => Some(500),
        'K' => Some(667),
        'L' => Some(556),
        'M' => Some(833),
        'N' => Some(722),
        'O' => Some(778),
        'P' => Some(667),
        'Q' => Some(778),
        'R' => Some(722),
        'S' => Some(667),
        'T' => Some(611),
        'U' => Some(722),
        'V' => Some(667),
        'W' => Some(944),
        'X' => Some(667),
        'Y' => Some(667),
        'Z' => Some(611),
        '[' => Some(278),
        '\\' => Some(278),
        ']' => Some(278),
        '^' => Some(469),
        '_' => Some(556),
        '`' => Some(222),
        'a' => Some(556),
        'b' => Some(556),
        'c' => Some(500),
        'd' => Some(556),
        'e' => Some(556),
        'f' => Some(278),
        'g' => Some(556),
        'h' => Some(556),
        'i' => Some(222),
        'j' => Some(222),
        'k' => Some(500),
        'l' => Some(222),
        'm' => Some(833),
        'n' => Some(556),
        'o' => Some(556),
        'p' => Some(556),
        'q' => Some(556),
        'r' => Some(333),
        's' => Some(500),
        't' => Some(278),
        'u' => Some(556),
        'v' => Some(500),
        'w' => Some(722),
        'x' => Some(500),
        'y' => Some(500),
        'z' => Some(500),
        '{' => Some(334),
        '|' => Some(260),
        '}' => Some(334),
        '~' => Some(584),
        _ => None,
    }
}

fn helvetica_bold_width(ch: char) -> Option<i32> {
    match ch {
        'á' | 'à' | 'â' | 'ä' | 'ã' => Some(556),
        'é' | 'è' | 'ê' | 'ë' => Some(556),
        'í' | 'ì' | 'î' | 'ï' => Some(278),
        'ó' | 'ò' | 'ô' | 'ö' | 'õ' => Some(611),
        'ú' | 'ù' | 'û' | 'ü' => Some(611),
        'ý' | 'ÿ' => Some(556),
        'Á' | 'À' | 'Â' | 'Ä' | 'Ã' => Some(722),
        'É' | 'È' | 'Ê' | 'Ë' => Some(667),
        'Í' | 'Ì' | 'Î' | 'Ï' => Some(278),
        'Ó' | 'Ò' | 'Ô' | 'Ö' | 'Õ' => Some(778),
        'Ú' | 'Ù' | 'Û' | 'Ü' => Some(722),
        'Ý' => Some(667),
        'ø' => Some(611),
        'Ø' => Some(778),
        'Ł' => Some(611),
        'ł' => Some(278),
        'ń' | 'ñ' => Some(611),
        'Ñ' => Some(722),
        '–' => Some(556),
        '—' => Some(1000),
        '’' => Some(278),
        ' ' => Some(278),
        '!' => Some(333),
        '"' => Some(474),
        '#' => Some(556),
        '$' => Some(556),
        '%' => Some(889),
        '&' => Some(722),
        '\'' => Some(278),
        '(' => Some(333),
        ')' => Some(333),
        '*' => Some(389),
        '+' => Some(584),
        ',' => Some(278),
        '-' => Some(333),
        '.' => Some(278),
        '/' => Some(278),
        '0' => Some(556),
        '1' => Some(556),
        '2' => Some(556),
        '3' => Some(556),
        '4' => Some(556),
        '5' => Some(556),
        '6' => Some(556),
        '7' => Some(556),
        '8' => Some(556),
        '9' => Some(556),
        ':' => Some(333),
        ';' => Some(333),
        '<' => Some(584),
        '=' => Some(584),
        '>' => Some(584),
        '?' => Some(611),
        '@' => Some(975),
        'A' => Some(722),
        'B' => Some(722),
        'C' => Some(722),
        'D' => Some(722),
        'E' => Some(667),
        'F' => Some(611),
        'G' => Some(778),
        'H' => Some(722),
        'I' => Some(278),
        'J' => Some(556),
        'K' => Some(722),
        'L' => Some(611),
        'M' => Some(833),
        'N' => Some(722),
        'O' => Some(778),
        'P' => Some(667),
        'Q' => Some(778),
        'R' => Some(722),
        'S' => Some(667),
        'T' => Some(611),
        'U' => Some(722),
        'V' => Some(667),
        'W' => Some(944),
        'X' => Some(667),
        'Y' => Some(667),
        'Z' => Some(611),
        '[' => Some(333),
        '\\' => Some(278),
        ']' => Some(333),
        '^' => Some(333),
        '_' => Some(556),
        '`' => Some(278),
        'a' => Some(556),
        'b' => Some(611),
        'c' => Some(556),
        'd' => Some(611),
        'e' => Some(556),
        'f' => Some(333),
        'g' => Some(611),
        'h' => Some(611),
        'i' => Some(278),
        'j' => Some(278),
        'k' => Some(556),
        'l' => Some(278),
        'm' => Some(889),
        'n' => Some(611),
        'o' => Some(611),
        'p' => Some(611),
        'q' => Some(611),
        'r' => Some(389),
        's' => Some(556),
        't' => Some(333),
        'u' => Some(611),
        'v' => Some(556),
        'w' => Some(778),
        'x' => Some(556),
        'y' => Some(556),
        'z' => Some(500),
        '{' => Some(389),
        '|' => Some(280),
        '}' => Some(389),
        '~' => Some(333),
        _ => None,
    }
}

fn times_roman_width(ch: char) -> Option<i32> {
    match ch {
        'á' | 'à' | 'â' | 'ä' | 'ã' => Some(444),
        'é' | 'è' | 'ê' | 'ë' => Some(444),
        'í' | 'ì' | 'î' | 'ï' => Some(278),
        'ó' | 'ò' | 'ô' | 'ö' | 'õ' => Some(500),
        'ú' | 'ù' | 'û' | 'ü' => Some(500),
        'ý' | 'ÿ' => Some(500),
        'Á' | 'À' | 'Â' | 'Ä' | 'Ã' => Some(722),
        'É' | 'È' | 'Ê' | 'Ë' => Some(611),
        'Í' | 'Ì' | 'Î' | 'Ï' => Some(333),
        'Ó' | 'Ò' | 'Ô' | 'Ö' | 'Õ' => Some(722),
        'Ú' | 'Ù' | 'Û' | 'Ü' => Some(722),
        'Ý' => Some(722),
        'ø' => Some(500),
        'Ø' => Some(722),
        'Ł' => Some(611),
        'ł' => Some(278),
        'ń' | 'ñ' => Some(500),
        'Ñ' => Some(722),
        '–' => Some(500),
        '—' => Some(1000),
        '’' => Some(333),
        ' ' => Some(250),
        '!' => Some(333),
        '"' => Some(408),
        '#' => Some(500),
        '$' => Some(500),
        '%' => Some(833),
        '&' => Some(778),
        '\'' => Some(180),
        '(' => Some(333),
        ')' => Some(333),
        '*' => Some(500),
        '+' => Some(564),
        ',' => Some(250),
        '-' => Some(333),
        '.' => Some(250),
        '/' => Some(278),
        '0' => Some(500),
        '1' => Some(500),
        '2' => Some(500),
        '3' => Some(500),
        '4' => Some(500),
        '5' => Some(500),
        '6' => Some(500),
        '7' => Some(500),
        '8' => Some(500),
        '9' => Some(500),
        ':' => Some(278),
        ';' => Some(278),
        '<' => Some(564),
        '=' => Some(564),
        '>' => Some(564),
        '?' => Some(444),
        '@' => Some(921),
        'A' => Some(722),
        'B' => Some(667),
        'C' => Some(667),
        'D' => Some(722),
        'E' => Some(611),
        'F' => Some(556),
        'G' => Some(722),
        'H' => Some(722),
        'I' => Some(333),
        'J' => Some(389),
        'K' => Some(722),
        'L' => Some(611),
        'M' => Some(889),
        'N' => Some(722),
        'O' => Some(722),
        'P' => Some(556),
        'Q' => Some(722),
        'R' => Some(667),
        'S' => Some(556),
        'T' => Some(611),
        'U' => Some(722),
        'V' => Some(722),
        'W' => Some(944),
        'X' => Some(722),
        'Y' => Some(722),
        'Z' => Some(611),
        '[' => Some(333),
        '\\' => Some(278),
        ']' => Some(333),
        '^' => Some(469),
        '_' => Some(500),
        '`' => Some(333),
        'a' => Some(444),
        'b' => Some(500),
        'c' => Some(444),
        'd' => Some(500),
        'e' => Some(444),
        'f' => Some(333),
        'g' => Some(500),
        'h' => Some(500),
        'i' => Some(278),
        'j' => Some(278),
        'k' => Some(500),
        'l' => Some(278),
        'm' => Some(778),
        'n' => Some(500),
        'o' => Some(500),
        'p' => Some(500),
        'q' => Some(500),
        'r' => Some(333),
        's' => Some(389),
        't' => Some(278),
        'u' => Some(500),
        'v' => Some(500),
        'w' => Some(722),
        'x' => Some(500),
        'y' => Some(500),
        'z' => Some(444),
        '{' => Some(480),
        '|' => Some(200),
        '}' => Some(480),
        '~' => Some(541),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::{standard_14_font_width, supports_standard_14_font};

    #[test]
    fn supports_corpus_standard_fonts() {
        assert!(supports_standard_14_font("Helvetica"));
        assert!(supports_standard_14_font("Helvetica-Bold"));
        assert!(supports_standard_14_font("Times-Roman"));
        assert!(supports_standard_14_font("Courier"));
        assert!(!supports_standard_14_font("Arial"));
    }

    #[test]
    fn returns_expected_extra_glyph_widths() {
        assert_eq!(standard_14_font_width("Helvetica-Bold", 'ó'), Some(611_i32));
        assert_eq!(standard_14_font_width("Courier", '–'), Some(600_i32));
        assert_eq!(standard_14_font_width("Times-Roman", '’'), Some(333_i32));
    }
}
