[package]
name = "unredact-web-bindings"
version = "0.1.0"
edition = "2021"
description = "WASM bindings for the UnRedact web entrypoint."
license-file = "../LICENSE"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde-wasm-bindgen = "=0.6.5"
wasm-bindgen = "=0.2.108"
unredact_core = { package = "unredact", path = "..", default-features = false, features = ["shared-bytes-workflow", "web-entry"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--all-features"]
